// Copyright 2026 OpenTalon Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package resources

import (
	"fmt"
	"strings"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v1alpha1 "github.com/opentalon/k8s-operator/api/v1alpha1"
)

// ConfigMapName returns the name of the ConfigMap holding config.yaml.
func ConfigMapName(instance *v1alpha1.OpenTalonInstance) string {
	return ResourceName(instance) + "-config"
}

// BuildConfigMap creates the ConfigMap that holds the rendered config.yaml for the instance.
// The YAML is constructed directly from the spec fields so no template engine dependency
// is required.
func BuildConfigMap(instance *v1alpha1.OpenTalonInstance) *corev1.ConfigMap {
	config := renderConfigYAML(instance)

	return &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{
			Name:      ConfigMapName(instance),
			Namespace: instance.Namespace,
			Labels:    Labels(instance),
		},
		Data: map[string]string{
			"config.yaml": config,
		},
	}
}

// renderConfigYAML produces a complete OpenTalon config.yaml string from the instance spec.
func renderConfigYAML(instance *v1alpha1.OpenTalonInstance) string {
	spec := instance.Spec.Config
	var sb strings.Builder

	sb.WriteString("# OpenTalon configuration — generated by opentalon-operator\n")
	sb.WriteString("# Do not edit manually; changes will be overwritten on next reconciliation.\n\n")

	// ── Models ────────────────────────────────────────────────────────────────
	if len(spec.Models) > 0 {
		sb.WriteString("models:\n")
		for _, m := range spec.Models {
			fmt.Fprintf(&sb, "  - name: %s\n", yamlString(m.Name))
			fmt.Fprintf(&sb, "    provider: %s\n", yamlString(m.Provider))
			if m.BaseURL != "" {
				fmt.Fprintf(&sb, "    base_url: %s\n", yamlString(m.BaseURL))
			}
			if m.ContextWindow > 0 {
				fmt.Fprintf(&sb,"    context_window: %d\n", m.ContextWindow)
			}
			if m.MaxTokens > 0 {
				fmt.Fprintf(&sb,"    max_tokens: %d\n", m.MaxTokens)
			}
			// API key is injected via env var; write the env var reference.
			if m.APIKeySecret != nil {
				envVar := apiKeyEnvVar(m.Provider)
				fmt.Fprintf(&sb,"    api_key_env: %s\n", envVar)
			}
		}
		sb.WriteString("\n")
	}

	// ── Routing ───────────────────────────────────────────────────────────────
	if spec.Routing != nil {
		sb.WriteString("routing:\n")
		if spec.Routing.Primary != "" {
			fmt.Fprintf(&sb,"  primary: %s\n", yamlString(spec.Routing.Primary))
		}
		if len(spec.Routing.Fallbacks) > 0 {
			sb.WriteString("  fallbacks:\n")
			for _, f := range spec.Routing.Fallbacks {
				fmt.Fprintf(&sb,"    - %s\n", yamlString(f))
			}
		}
		sb.WriteString("\n")
	}

	// ── Channels ──────────────────────────────────────────────────────────────
	if spec.Channels != nil {
		sb.WriteString("channels:\n")

		if spec.Channels.Console != nil {
			sb.WriteString("  console:\n")
			fmt.Fprintf(&sb,"    enabled: %v\n", spec.Channels.Console.Enabled)
		}

		if spec.Channels.Slack != nil {
			sb.WriteString("  slack:\n")
			fmt.Fprintf(&sb,"    enabled: %v\n", spec.Channels.Slack.Enabled)
			// Token is mounted via env; reference the env var name OpenTalon expects.
			sb.WriteString("    token_env: SLACK_BOT_TOKEN\n")
			if spec.Channels.Slack.AppTokenSecret != nil {
				sb.WriteString("    app_token_env: SLACK_APP_TOKEN\n")
			}
		}

		if spec.Channels.Webhook != nil {
			sb.WriteString("  webhook:\n")
			fmt.Fprintf(&sb,"    enabled: %v\n", spec.Channels.Webhook.Enabled)
			port := spec.Channels.Webhook.Port
			if port == 0 {
				port = 8080
			}
			fmt.Fprintf(&sb,"    port: %d\n", port)
			path := spec.Channels.Webhook.Path
			if path == "" {
				path = "/webhook"
			}
			fmt.Fprintf(&sb,"    path: %s\n", yamlString(path))
		}

		if spec.Channels.WebSocket != nil {
			sb.WriteString("  websocket:\n")
			fmt.Fprintf(&sb,"    enabled: %v\n", spec.Channels.WebSocket.Enabled)
			port := spec.Channels.WebSocket.Port
			if port == 0 {
				port = 8081
			}
			fmt.Fprintf(&sb,"    port: %d\n", port)
			wsPath := spec.Channels.WebSocket.Path
			if wsPath == "" {
				wsPath = "/ws"
			}
			fmt.Fprintf(&sb,"    path: %s\n", yamlString(wsPath))
			if len(spec.Channels.WebSocket.CORSOrigins) > 0 {
				sb.WriteString("    cors_origins:\n")
				for _, o := range spec.Channels.WebSocket.CORSOrigins {
					fmt.Fprintf(&sb,"      - %s\n", yamlString(o))
				}
			}
		}

		sb.WriteString("\n")
	}

	// ── Plugins ───────────────────────────────────────────────────────────────
	// Plugin runtime configuration (source, github/ref, config) is not rendered
	// here — it belongs in the external ConfigMap (configFrom) or extraConfig.
	// The CRD PluginConfig only manages Kubernetes-level resources (ingress,
	// service port).

	// ── State ─────────────────────────────────────────────────────────────────
	if spec.State != nil {
		sb.WriteString("state:\n")
		path := spec.State.Path
		if path == "" {
			path = "/data/opentalon.db"
		}
		fmt.Fprintf(&sb,"  path: %s\n", yamlString(path))
		if spec.State.MaxMessages != nil {
			fmt.Fprintf(&sb,"  max_messages: %d\n", *spec.State.MaxMessages)
		}
		if spec.State.IdleSessionTTL != "" {
			fmt.Fprintf(&sb,"  idle_session_ttl: %s\n", yamlString(spec.State.IdleSessionTTL))
		}
		if spec.State.Summarize {
			sb.WriteString("  summarize: true\n")
		}
		sb.WriteString("\n")
	} else {
		// Default state config always written so the process has a valid db path.
		sb.WriteString("state:\n")
		sb.WriteString("  path: /data/opentalon.db\n\n")
	}

	// ── Logging ───────────────────────────────────────────────────────────────
	if spec.Logging != nil {
		sb.WriteString("logging:\n")
		level := spec.Logging.Level
		if level == "" {
			level = "info"
		}
		fmt.Fprintf(&sb,"  level: %s\n", level)
		format := spec.Logging.Format
		if format == "" {
			format = "json"
		}
		fmt.Fprintf(&sb,"  format: %s\n", format)
		sb.WriteString("\n")
	} else {
		sb.WriteString("logging:\n")
		sb.WriteString("  level: info\n")
		sb.WriteString("  format: json\n\n")
	}

	// ── Health ────────────────────────────────────────────────────────────────
	// Always render the health block so the gRPC probe server binds to the
	// port the operator configured in the container/probe specs.
	{
		p := instance.Spec.Observability.Health.Port
		if p == 0 {
			p = 8086
		}
		sb.WriteString("health:\n")
		fmt.Fprintf(&sb, "  addr: \":%d\"\n\n", p)
	}

	// ── Metrics ──────────────────────────────────────────────────────────────
	if instance.Spec.Observability.Metrics.Enabled != nil && *instance.Spec.Observability.Metrics.Enabled {
		sb.WriteString("metrics:\n")
		sb.WriteString("  enabled: true\n")
		p := instance.Spec.Observability.Metrics.Port
		if p == 0 {
			p = 9090
		}
		fmt.Fprintf(&sb, "  addr: \":%d\"\n\n", p)
	}

	// ── Extra config (raw append) ─────────────────────────────────────────────
	if spec.ExtraConfig != "" {
		sb.WriteString("# Extra configuration supplied via spec.config.extraConfig\n")
		sb.WriteString(spec.ExtraConfig)
		if !strings.HasSuffix(spec.ExtraConfig, "\n") {
			sb.WriteString("\n")
		}
	}

	return sb.String()
}

// apiKeyEnvVar returns the conventional environment variable name for a given provider's API key.
func apiKeyEnvVar(provider string) string {
	switch strings.ToLower(provider) {
	case "anthropic":
		return "ANTHROPIC_API_KEY"
	case "openai":
		return "OPENAI_API_KEY"
	case "deepseek":
		return "DEEPSEEK_API_KEY"
	case "cohere":
		return "COHERE_API_KEY"
	case "gemini", "google":
		return "GEMINI_API_KEY"
	default:
		return strings.ToUpper(provider) + "_API_KEY"
	}
}

// yamlString wraps a string value in double-quotes if it contains characters that
// could confuse a YAML parser (colons, leading/trailing whitespace, special chars).
// For simple alphanumeric values no quoting is applied.
func yamlString(s string) string {
	if s == "" {
		return `""`
	}
	// Quote if the string contains characters that need escaping in YAML flow context.
	needsQuote := false
	for _, ch := range s {
		if ch == ':' || ch == '#' || ch == '{' || ch == '}' || ch == '[' || ch == ']' ||
			ch == ',' || ch == '&' || ch == '*' || ch == '?' || ch == '|' || ch == '-' ||
			ch == '<' || ch == '>' || ch == '=' || ch == '!' || ch == '%' || ch == '@' ||
			ch == '`' || ch == '\'' || ch == '"' {
			needsQuote = true
			break
		}
	}
	if strings.HasPrefix(s, " ") || strings.HasSuffix(s, " ") {
		needsQuote = true
	}
	if needsQuote {
		escaped := strings.ReplaceAll(s, `\`, `\\`)
		escaped = strings.ReplaceAll(escaped, `"`, `\"`)
		return `"` + escaped + `"`
	}
	return s
}
