apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentalon-operator-controller-manager
  namespace: opentalon-operator-system
  labels:
    app.kubernetes.io/name: opentalon-operator
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/managed-by: kustomize
